CORETest/Areas/Admin/Models/PostViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CORETest.Areas.Admin.Models
{
	public class PostViewModel
	{
		public int Id { get; set; }
		public DateTime CreationDate { get; set; }
		public bool IsDelete { get; set; }
		public int UserId { get; set; }
		public int CategoryId { get; set; }
		public int SubCategoryId { get; set; }
		public string Title { get; set; }
		public string Slug { get; set; }
		public string Description { get; set; }
		public int Visit { get; set; }
		public string Photo1 { get; set; }
		public string Photo2 { get; set; }
	}
}

CORETest/Areas/Admin/Controllers/PostsController.cs
using CoreLayer.DTOs.Posts;
using CoreLayer.Services.Categories;
using CoreLayer.Utilities;
using CORETest.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace CORETest.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Authorize]
	public class PostsController : Controller
	{
		private readonly IPostservices _postservices;
		public PostsController(IPostservices postservices)
		{
			_postservices = postservices;
		}
		public IActionResult Index(int pageid = 1, string title = "", string categorySlug = "")
		{
			return View(_postservices.GetPostsByFilter(new PostFilterParams()
			{
				CategorySlug = categorySlug,
				PageId = pageid,
				Title = title,
				Take = 2
			}));
		}

		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(CreatePostViewModel createPostViewModel)
		{
			if (ModelState.IsValid)
			{
				var postDTO = new CreatePostDTO()
				{
					Photo1 = createPostViewModel.Photo1,
					Slug = createPostViewModel.Slug,
					Title = createPostViewModel.Title,
					CategoryId = createPostViewModel.CategoryId,
					Description = createPostViewModel.Description,
					IsDelete = false,
					UserId = User.GetUserID(),
					SubCategoryId = createPostViewModel.SubCategoryId
				};
				var res = _postservices.CreatePost(postDTO);
			}
			return RedirectToAction("Index");
		}
		public IActionResult Edit(int id)
		{
			var post = _postservices.GetPostByid(id);
			var model = new EditPostViewModel()
			{
				id = id,
				CategoryId = post.CategoryId,
				Description = post.Description,
				Slug = post.Slug,
				SubCategoryId = post.SubCategoryId,
				Title = post.Title
			};
			ViewData["PIC1"] = post.Photo1;
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit(EditPostViewModel EditVM)
		{
			var post = new EditPostDTO()
			{
				Id = EditVM.id,
				CategoryId = EditVM.CategoryId,
				Description = EditVM.Description,
				SubCategoryId = EditVM.SubCategoryId,
				Photo1 = EditVM.Photo1,
				//Photo2 = EditVM.Photo2,
				Slug = EditVM.Slug,
				Title = EditVM.Title
			};
			var res = _postservices.EditPost(post);
			if (res.Status == Utilities.OperationResultStatus.Success)
			{
				return RedirectToAction("Index");
			}
			return View();
		}
		public IActionResult Delete(int id)
		{
			var model = _postservices.GetPostByid(id);
			var modelVM = new PostViewModel()
			{
				CategoryId = model.CategoryId,
				CreationDate = model.CreationDate,
				Description = model.Description,
				Id = model.Id,
				IsDelete = model.IsDelete,
				Photo1 = model.Photo1,
				Photo2 = model.Photo2,
				Slug = model.Slug,
				SubCategoryId = model.SubCategoryId,
				Title = model.Title,
				Visit = model.Visit
			};
			return PartialView(modelVM);
		}
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Delete(PostViewModel PostVM)
		{
			var res = _postservices.DeletePost(PostVM.Id);
			if (res.Status == Utilities.OperationResultStatus.Success)
			{
				return RedirectToAction("Index");
			}
			else
			{
				return View(PostVM);
			}
		}
		[Route("/Upload/Article")]
		public IActionResult Ckeditorimage(IFormFile Upload)
		{
			string filename;
			if (Upload != null)
			{
				filename = _postservices.SaveImg(Upload);
				return Json(new { Uploaded = true, Url = $"/images/{filename}" });
			}
			return null;
		}
		public IActionResult PostCount()
		{
			return new JsonResult(_postservices.GetCountOfPosts());
		}
	}
}

CORETest/Pages/Post.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreLayer.DTOs.PostComments;
using CoreLayer.DTOs.Posts;
using CoreLayer.Services.Categories;
using CoreLayer.Services.PostComments;
using CoreLayer.Services.Users;
using CoreLayer.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CORETest.Pages
{
	public class PostModel : PageModel
	{
		private IPostCommentservices PCS;
		private IPostservices _postservices;
		public PostModel(IPostservices postservices, IPostCommentservices postCommentservices)
		{
			_postservices = postservices;
			PCS = postCommentservices;
		}

		public PostDTO post { get; set; }
		[BindProperty]
		public int PostId { get; set; }
		[BindProperty]
		public string Text { get; set; }

		public IEnumerable<PostDTO> Releatedposts;
		public IEnumerable<CommentDTO> comments;

		public IActionResult OnGet(string slug)
		{
			if (slug == null)
				return NotFound();

			post = _postservices.GetPostBySlug(slug);
			comments = PCS.GetComments(post.Id);
			Releatedposts = _postservices.GetRelatedPosts(post.SubCategoryId, post.CategoryId);
			return Page();
		}

		public IActionResult OnPost(string slug)
		{
			if (!User.Identity.IsAuthenticated)
			{
				return RedirectToPage("Post", new { slug });
			}
			PCS.AddComment(new AddcommentDTO()
			{
				PostId = PostId,
				Text = Text,
				UserId = User.GetUserID()
			});
			
			return RedirectToPage("Post", new { slug });
		}
	}
}

CORETest/Areas/Admin/Views/Posts/Create.cshtml
@model Areas.Admin.Models.CreatePostViewModel
@{
    @using CoreLayer.Services.Categories;
    @inject ICategoryservices _Categoryservice;
    var category = _Categoryservice.GetAllCategories();
}

<div class="box box-primary ">
    <div class="box-header with-border">
        <h3 class="box-title">پست جدید</h3>
    </div>

    <form method="post" asp-area="Admin" asp-controller="Posts" asp-action="Create" enctype="multipart/form-data">
        <div class="box-body col-md-6">
            <div class="form-group">
                <label asp-for="Title" for="exampleInputEmail1"></label>
                <input asp-for="Title" class="form-control" placeholder="">
            </div>
            <div class="form-group ">
                <div class="form-group col-md-4">
                    <label asp-for="Photo1" for="exampleInputFile"></label>
                    <div id="wrapper" style="margin-top: 20px;">
                        <input asp-for="Photo1" type="file" id="Photo1" name="Photo1" />
                        <div id="image-holder1"></div>
                    </div>
                </div>
                <div class="form-group col-md-4">
                    <label asp-for="Photo2" for="exampleInputFile"></label>
                    <div id="wrapper" style="margin-top: 20px;">
                        <input asp-for="Photo2" type="file" id="Photo2" name="Photo2" />
                        <div id="image-holder2"></div>
                    </div>
                </div>
            </div>
            <br />
        </div>

        <div class="box-body col-md-6">
            <div class="form-group ">
                <label asp-for="Slug" for="exampleInputEmail1"></label>
                <input asp-for="Slug" class="form-control" placeholder="">
            </div>
        </div>
        <div class="box-body col-md-6">
            <div class="col-md-6">
                <label asp-for="CategoryId" for="exampleInputEmail1"></label>
                <select asp-for="CategoryId" class="form-control">
                    <option value="null">انتخاب کنید</option>
                    @foreach (var item in category.Where(c => c.ParentID == null))
                    {
                        <option value="@item.Id">@item.Title</option>
                    }
                </select>
            </div>

            <div class="col-md-6">
                <label asp-for="SubCategoryId" for="exampleInputEmail1"></label>
                <select asp-for="SubCategoryId" class="form-control">
                    <option value="null">انتخاب کنید</option>
                </select>

            </div>
        </div>

        <div class="box-body col-md-12">
            <div class="form-group ">
                <label asp-for="Description"></label>
                <textarea asp-for="Description" id="Ckeditor" class="form-control" rows="3" style="min-width:100% "></textarea>
            </div>
        </div>

        <br />
        <div class="box-footer ">
            <button type="submit" value="Upload" class="btn btn-primary btn-lg" style="width:100%">ثـبـت</button>
        </div>
    </form>
</div>

<script src="~/js/jquery.min.js"></script>
<script>
    $("#CategoryId").change(function () {
        var categoryid = $(this).val();
        $.ajax({
            type: "Get",
            url: "/admin/categories/GetChildCatefories?parentID=" + categoryid
        }).done(function (response) {
            $("#SubCategoryId").html(`<option value='null'>انتخاب کنید</option>`);
            for (var i in response) {
                var category = response[i];
                $("#SubCategoryId").append(`<option value='${category.id}'>${category.title}</option>`);
            }
        });
    });
</script>

CORETest/Areas/Admin/Views/Posts/Delete.cshtml
@model CORETest.Areas.Admin.Models.PostViewModel
@{
    @using CoreLayer.Services.Categories;
    @inject ICategoryservices _Categoryservice;
    var Allcategory = _Categoryservice.GetAllCategories();
    var category = Allcategory.SingleOrDefault(c => c.ParentID == Model.CategoryId);
    var Subcategory = Allcategory.SingleOrDefault(c => c.Id == Model.SubCategoryId);
}


<form method="post" asp-area="Admin" asp-controller="Posts" asp-action="Delete">
    <fieldset disabled>
        <legend class="danger">آیا از حـذف @Model.Title مـطـمئـن هـسـتـید؟</legend>
        <div class="box-body">
            <div class="col-md-6">
                <div col-md-6">
                    <label for="disabledTextInput" class="form-label">تصـوِیـر</label>
                    <img style="max-width:100%" class="thumbnail" src="~/images/posts/@Model.Photo1 " />
                </div>

            </div>
            <div class="col-md-6">
                <div col-md-4">
                    <label for="disabledTextInput" class="form-label">Slug</label>
                    <input asp-for="Slug" type="text" class="form-control" placeholder="@Model.Slug">
                </div>
                <br />
                <div class="col-md-4">

                    <div >
                        <label for="disabledSelect" class="form-label">گـروه</label>
                        <select id="disabledSelect" class="form-select">
                            <option>@category.Title</option>
                        </select>
                    </div>
                    <div >
                        <label for="disabledSelect" class="form-label">زیـر گـروه</label>
                        <select id="disabledSelect" class="form-select">
                            <option>@Subcategory.Title</option>
                        </select>
                    </div>

                    <br />
                </div>
                <div class="col-md-4">
                    <label for="disabledTextInput" class="form-label">بازدید</label>
                    <input asp-for="Visit" type="text" class="form-control" placeholder="@Model.Visit">
                </div>

            </div>
        </div>
    </fieldset>
    <div class="box-footer ">
        <button type="submit" class="btn btn-danger btn-lg" style="width:100%">حـذف</button>
    </div>
</form>

CORETest/Areas/Admin/Views/Posts/Edit.cshtml
@model CORETest.Areas.Admin.Models.EditPostViewModel
@{
    @using CoreLayer.Services.Categories;
    @inject ICategoryservices _Categoryservice;
    var category = _Categoryservice.GetAllCategories();
}
<section>
    <div class="row-10">
        <div class="box box-primary ">
            <div class="box-header with-border">
                <h3 class="box-title">پست جدید</h3>
            </div>

            <form method="post" asp-area="Admin" asp-controller="Posts" asp-action="Edit" enctype="multipart/form-data">
                <div class="box-body col-md-6">
                    <div class="form-group">
                        <label asp-for="Title" for="exampleInputEmail1"></label>
                        <input asp-for="Title" class="form-control" placeholder="">
                    </div>
                    <div class="form-group ">
                        <div class="form-group col-md-4">
                            <label asp-for="Photo1" for="exampleInputFile"></label>
                            <div id="wrapper" style="margin-top: 20px;">
                                <input asp-for="Photo1" type="file" id="Photo1" name="Photo1" />
                                <img class="thumbnail" src="~/images/posts/@ViewData["PIC1"]" />
                                <div id="image-holder1" style="max-width:100%"></div>
                            </div>
                        </div>
                        @*<div class="form-group col-md-4">
                            <label asp-for="Photo2" for="exampleInputFile"></label>
                            <div id="wrapper" style="margin-top: 20px;">
                                <input asp-for="Photo2" type="file" id="Photo2" name="Photo2" />
                                <div id="image-holder2"></div>
                            </div>
                        </div>*@
                    </div>
                    <br />
                </div>

                <div class="box-body col-md-6">
                    <div class="form-group ">
                        <label asp-for="Slug" for="exampleInputEmail1"></label>
                        <input asp-for="Slug" class="form-control" placeholder="">
                    </div>
                </div>
                <div class="box-body col-md-6">
                    <div class="col-md-6">
                        <label asp-for="CategoryId" for="exampleInputEmail1"></label>
                        <select asp-for="CategoryId" class="form-control">
                            <option>انتخاب کنید</option>
                            @foreach (var item in category.Where(c => c.ParentID == null))
                            {
                                <option value="@item.Id">@item.Title</option>
                            }
                        </select>
                    </div>

                    <div class="col-md-6">
                        <label asp-for="SubCategoryId" for="exampleInputEmail1"></label>
                        <select asp-for="SubCategoryId" class="form-control">
                            <option value="0">انتـخـاب کـنـیـد</option>
                        </select>

                    </div>
                </div>

                <div class="box-body col-md-12">
                    <div class="form-group ">
                        <label asp-for="Description"></label>
                        <textarea asp-for="Description" id="Ckeditor" class="form-control" rows="3" style="min-width:100% "></textarea>
                    </div>
                </div>

                <br />
                <div class="box-footer ">
                    <button type="submit" class="btn btn-primary btn-lg" style="width:100%">ثـبـت</button>
                </div>
            </form>
        </div>

    </div>
</section>

<script src="~/js/jquery.min.js"></script>
<script>
    $("#CategoryId").change(function () {
        var categoryid = $(this).val();
        $.ajax({
            type: "Get",
            url: "/admin/categories/GetChildCatefories?parentID=" + categoryid
        }).done(function (response) {
            $("#SubCategoryId").html(`<option >انتخاب کنید</option>`);
            for (var i in response) {
                var category = response[i];
                $("#SubCategoryId").append(`<option value='${category.id}'>${category.title}</option>`);
            }
        });
    });
</script>

CORETest/Areas/Admin/Views/Posts/Index.cshtml
@model CoreLayer.DTOs.Posts.PostFilterDto
@{
    int Counter = 1;

}
<!-- Modal -->
<div class="modal fade" id="MyModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" id="modalbody">

            </div>

        </div>
    </div>
</div>

<section>
    <div class="box box-danger">
        <div class="box-body">
            <form>
                <div class="box-header">
                    <button type="submit" class="btn btn-info pull-left">فیلتر </button>
                </div>
                <div class="row">
                    <div class="col-md-6 form-group">
                        <input class="form-control" type="text" value="@Model.FilterParams.Title" placeholder="عنوان" name="title" />
                    </div>
                    <div class="col-md-6 form-group">
                        <input class="form-control" type="text" value="@Model.FilterParams.CategorySlug" placeholder="Slug Category" name="categorySlug" />
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="box">
        <div class="box-header with-border">
            <h2 class="box-title">Category</h2>
        </div>
        &nbsp;&nbsp;<a href="/Admin/posts/Create" class="btn btn-success" style="margin-top:8px">افـزودن پـسـت جـدیـد</a>
        <div class="box-body">

            <table class="table table-bordered table-striped dataTable">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>تصویر</th>
                        <th>عنوان</th>
                        <th>گروه</th>
                        <th>زیر گروه</th>
                        <th>عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Posts)
                    {
                        <tr>
                            <td>@Counter</td>
                            <th style="max-height:150px"><img class="thumbnail" style="max-width:100px" src="/images/posts/@item.Photo1" /></th>
                            <td>@item.Title</td>
                            <td>@item.CategoryId</td>
                            <th>@item.SubCategoryId</th>
                            <td>
                                <a href="/Admin/posts/Edit/@item.Id" class="btn btn-warning">ویـرایـش</a> &nbsp;
                                <a class="btn btn-danger" onclick="deletePost(@item.Id)">حــذف</a>
                            </td>
                        </tr>
                        Counter++;
                    }
                </tbody>
            </table>
        </div>
    </div>

    @if (Model.PageCount > 1)
    {
        <div class="box-footer">
            <div style="padding:10px">
                <ul class="pagination" style="display: inline-block">
                    @if (Model.FilterParams.PageId > 1)
                    {
                        <li class="paginate_button previous">
                            <a onclick="changePage(@(Model.FilterParams.PageId-1))" href="#">قبلی</a>
                        </li>
                    }
                    else
                    {

                        <li class="paginate_button previous disabled">
                            <a href="#">قبلی</a>
                        </li>
                    }

                    @for (var i = 1; i <= Model.PageCount; i++)
                    {
                        <li class="paginate_button @(i == Model.FilterParams.PageId ? "active" : null)">
                            <a onclick="changePage(@i)" href="javascript:void(0)">@i</a>
                        </li>
                    }
                    @if (Model.PageCount > Model.FilterParams.PageId)
                    {
                        <li class="paginate_button next">
                            <a onclick="changePage(@(Model.FilterParams.PageId+1))" href="#">بعدی</a>
                        </li>
                    }
                    else
                    {
                        <li class="paginate_button next disabled">
                            <a href="javascript:void(0)">بعدی</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    }
</section>

<script>

    function changePage(pageId) {
        var url = new URL(window.location.href);
        var search_params = url.searchParams;

        // Change PageId
        search_params.set('pageId', pageId);
        url.search = search_params.toString();

        // the new url string
        var new_url = url.toString();

        window.location.replace(new_url);
    }


    function deletePost(id) {
        $.ajax({
            type: "get",
            url: "/Admin/Posts/Delete/" + id
        }).done(function (res) {
            $("#MyModal").modal();
            $("#modalbody").html(res);
        });
    }

</script>